<div class="container" style="border-top:1px #C4D5DF solid;padding-top:1rem;margin-bottom:1rem;">
    <div class="row">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 text-center">
            <p class="text-center">Copyright &#169; 2016 - <?= date('Y') ?> 设计者 Chris Mao(Zibing) 保留所有权利</p>
            <!-- p class="text-center">Designer & Developer: Chris Mao(Zibing)</p -->
        </div>
    </div>
</div>
