<div class="row">
    <div class="col-lg-4 col-lg-offset-4 col-md-4 col-md-offset-4 col-sm-6 col-md-offset-6 col-xs-4 col-xs-offset-4">
        <div class="form-signin text-center" style="font-size:24px;">
            <span class="emerson"></span>
            <p style="display:block;margin-top:40px;"><?php echo $this->translate('您已退出系统！！');?></p>
            <!--p style="display:block;margin:10px;">购物车中的产品已保存在服务器上，方便您下次购买。</p-->
            <p style="display:block;margin:10px;">三秒后自动转到<a style="margin-left:4px;" href="#">登录页面</a></p>
        </div>
    </div>
</div>
