<?php $this->headTitle($this->translate('受限访问')); ?>

<div class='page-header'>
    <h1 class='text-warning'><?= $this->translate('受限访问');?>
        <small class='text-info'>
        <?= $this->translate('您没有权限访问当前页面。'); ?>
        </small>
    </h1>
</div>

<div class='row text-muted text-center'>
    <div class='col-lg-12 col-md-12 col-sm-12 col-xs-12'>
        <p><?= $this->translate('亲，看到这个页面时请不要慌张，这并不代表您做错了什么，只是您没有获得访问权限。请与我们的客服专员联系，获取相应的访问权限。'); ?></p>
        <p><?php echo $this->content ?></p>
    </div>
</div>