<link rel="stylesheet" href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<div align='center' style='width:200px;margin:20px auto;display:block;'><img src='cid:logo-file' ></div>

<div style="margin:3rem auto;">
    您好 <?=$this->user?>，您收到一份来自 上海宏谷于 的采购订单，详情如下。
</div>

<p>
Thank you for placing an order with Emerson Climate Technologies, Inc.  Your order details are provided in the attachment.
</p>
<p>
This order shall be governed by Seller's standard terms and conditions of sale which are attached and can be found at <a href="www.emersonclimate.com">www.emersonclimate.com</a>.
</p>
<p>
Prices are subject to change and will be those in effect at time of shipment.
</p>

<div class="row" >
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
        <h1 class="text-center">艾默生环境优化技术（苏州）有限公司销售订单</h1>
    </div>
</div>

<div class="row" >
    <div class="col-sm-6 col-md-3 col-lg-3">
        <label>OU:</label>
        <span>EMR OU COPE SZ</span>
    </div>
    <div class="col-sm-6 col-md-3 col-lg-3">
        <label>SO#:</label>
        <span>310001234</span>
    </div>
    <div class="col-sm-6 col-md-3 col-lg-3">
        <label>Cust. Account:</label>
        <span>1200020690</span>
    </div>
    <div class="col-sm-6 col-md-3 col-lg-3 text-right">
        <label>Order Date:</label>
        <span>2017-03-03</span>
    </div>
</div>

<div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
        <table class="table table-bordered table-condensed">
            <tr>
                <td class="active" style="width:10rem;">
                    <label>客户订单</label>
                </td>
                <td colspan="6">Customer PO Number</td>
            </tr>
            <tr>
                <td class="active" style="width:10rem;">
                    <label>客户名称</label>
                </td>
                <td colspan="6">CUSTOMER_NAME</td>
            </tr>
            <tr>
                <td class="active">
                    <label>发票地址</label>
                </td>
                <td colspan="6">BILL_TO</td>
            </tr>
            <tr>
                <td class="active">
                    <label>销售地址</label>
                </td>
                <td colspan="6">SHIP_TO</td>
            </tr>
            <tr>
                <td class="active">
                    <label>送货地址</label>
                </td>
                <td colspan="6">DELIVER_TO</td>
            </tr>
            <tr>
                <th>Model Name</th>
                <th>Model Description</th>
                <th>Selling Price</th>
                <th>Qty</th>
                <th>Sub Total</th>
                <!-- <th>VAT');?></th> -->
                <th>Request Date</th>
                <th>Remark</th>
            </tr>
            <?php foreach ($orderLines as $line): ?>
                <tr>
                    <td><strong>MODEL_NAME</strong></td>
                    <td>ITEM_DESCRIPTION</td>
                    <td class='number small-bold-red text-right'>PRICE</td>
                    <td class='number small-bold-red text-right'>QTY</td>
                    <td class='number small-bold-red text-right'>TOTAL_AMOUNT</td>
                    <td>RTD</td>
                    <td class='text-info'>REMARK</td>
                </tr>
            <?php endforeach ?>            
        </table>
    </div>
</div>

<div class="row" >
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
        <!-- <p class="text-right">
            <a href='<?=$this->serverUrl()?>'>点击这里下载PDF格式订单文件</a>
        </p> -->
        <p class="text-right">
            <a href='<?=$this->serverUrl()?>'><small>点击这里登录Emerson Oracle处理订单</small></a>
        </p>
        <p class="text-right" style="color:gray;"><small>此邮件由系统自动发送，请勿回复</small></p>
    </div>
</div>