<?php $this->headTitle($this->translate('首页')); ?>

<div class="jumbotron">
    <h1>Welcome to <span class="zf-green">Zend Framework</span></h1>

    <p>
        Congratulations! You have successfully installed the
        <a href="https://github.com/zendframework/ZendSkeletonApplication" target="_blank">ZF Skeleton Application</a>.
        You are currently running Zend Framework version <?= \Application\Module::VERSION ?>.
        This skeleton can serve as a simple starting point for you to begin
        building your application on ZF.
    </p>

    <p><a class="btn btn-success btn-lg" href="https://github.com/zendframework/zendframework" target="_blank">Fork Zend Framework on GitHub &raquo;</a></p>
</div>

<div class="row">

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Follow Development</h3>
            </div>
            <div class="panel-body">
                <p>
                    Zend Framework is under active development. If you are
                    interested in following the development of ZF, you can check
                    <a href="http://framework.zend.com/blog/">ZF dev blog</a>,
                    and <a href="https://github.com/issues?utf8=%E2%9C%93&amp;q=is:issue+org:zendframework">ZF issue tracker</a>
                    (link requires a GitHub account). This is a great resource
                    for staying up to date with the latest developments!
                </p>

                <p><a class="btn btn-success pull-right" href="http://framework.zend.com/" target="_blank">ZF Development Portal &raquo;</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Discover Modules</h3>
            </div>
            <div class="panel-body">
                <p>
                    The community is working on developing a community site to
                    serve as a repository and gallery for ZF modules. The
                    project is available <a href="https://github.com/zendframework/modules.zendframework.com">on GitHub</a>.
                    The site is currently live and currently contains a list of
                    some of the modules already available for ZF.
                </p>

                <p><a class="btn btn-success pull-right" href="http://modules.zendframework.com/" target="_blank">Explore ZF Modules &raquo;</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Help &amp; Support</h3>
            </div>
            <div class="panel-body">
                <p>
                    If you need any help or support while developing with ZF,
                    you may reach us via IRC: <a href="irc://irc.freenode.net/zftalk">#zftalk on Freenode</a>.
                    We'd love to hear any questions or feedback you may have
                    regarding this release. Alternatively, you may subscribe
                    and post questions to the <a href="http://framework.zend.com/archives/">mailing lists</a>.
                </p>

                <p><a class="btn btn-success pull-right" href="http://webchat.freenode.net?channels=zftalk" target="_blank">Ping us on IRC &raquo;</a></p>
            </div>
        </div>
    </div>
</div>


<div class="row">
    <div class="col-md-4">
        <div class="panel panel-success">
            <div class="panel-heading">
                <h3 class="panel-title"><?= $this->translate('系统设置 & 管理');?></h3>
            </div>
            <div class="panel-body">
                <p><?= $this->translate('管理员通过这个入口可以管理网站用户帐号，同时还可以为客服人员、销售人员分配客户，使其可以透过这个网站查看客户的销售订单。有新的客户、亦或是销售加入，请联系管理员为您分配登录帐号。');?></p>
                <p>
                    <a class="btn btn-success pull-right" href="#" target="_blank">
                        <span class="glyphicon glyphicon-wrench"></span>&nbsp;<?= $this->translate('管理员请进');?> &raquo;
                    </a>
                </p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-success">
            <div class="panel-heading">
                <h3 class="panel-title"><?= $this->translate('订单管理');?></h3>
            </div>
            <div class="panel-body">
                <p><?= $this->translate('无论您是我们尊敬的客户、帅气的销售，亦或是我们美丽的客服同事，都可以从这个入口查询到相应的销售订单。如果订单数据有任何疑问，可以发送邮件到<a href="">毛子兵</a>，我们会以最快的速度通过电话或是邮件联系到您。');?></p>
                <p>
                    <a class="btn btn-success pull-right" href="#" target="_blank">
                        <span class="glyphicon glyphicon-search"></span>&nbsp;<?= $this->translate('订单查询');?> &raquo;
                    </a>
                </p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-success">
            <div class="panel-heading">
                <h3 class="panel-title"><?= $this->translate('满意度调查');?></h3>
            </div>
            <div class="panel-body">
                <p><?= $this->translate('问卷还在路上，请耐心等待......');?></p>
                <p>
                    <a class="btn btn-success pull-right" disabled="disabled" href="#" target="_blank">
                        <span class="glyphicon glyphicon-tasks"></span>&nbsp;<?= $this->translate('暂未开放');?> &raquo;
                    </a>
                </p>
            </div>
        </div>
    </div>

    <div>
        <ul>
            <li>单元测试请看<a target="_blank" href="https://docs.zendframework.com/tutorials/unit-testing/">这里</a></li>
            <li>多数据源配置<a target="_blank" href="https://docs.zendframework.com/tutorials/db-adapter/#installing-zend-db">这里</a> </li>
        </ul>
    </div>
</div>

